packages:
  - 'apps/*'
  - 'packages/*'
  - 'services/*'

catalog:
  react: ^18.2.0
  react-dom: ^18.2.0
  next: ^14.0.0
  typescript: ^5.3.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  '@types/node': ^20.10.0
  tailwindcss: ^3.4.0
  prettier: ^3.1.0
  eslint: ^8.55.0
  date-fns: ^2.30.0 